### ISSUE TITLE
JS Key Chain

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/ipfs-encryption#6]
Implement a key store #2 in JavaScript. See the [doc](https://github.com/richardschneider/ipfs-encryption/blob/master/src/keystore.md), [code](https://github.com/richardschneider/ipfs-encryption/blob/master/src/keystore.js) and [spec](https://github.com/richardschneider/ipfs-encryption/blob/master/test/keystore.spec.js)

It must

- [x] Manage a key (create, delete, list)
- [x] Import/Export a key
- [x] Encrypt/Decrypt a stream of data with a key
- [x] Create a PKCS 7 CMS message

It could
- [ ] Sign/Verify a stream of data with a key

**Comment by RangerMauve** [comment]
Is this going to adhere to what was already done for the [golang implementation](https://ipfs.io/docs/commands/#ipfs-key)?

**Comment by richardschneider** [comment]
@RangerMauve Yes, the `ipfs key` commands will be implemented.  Here's a more updated [spec](https://github.com/ipfs/specs/tree/master/keystore).

Also need  `ipfs key export` and `ipfs key import` commands.

**Comment by richardschneider** [comment]
@RangerMauve  Encrypted PubSub is easy with CMS.  Simply convert the topic message (plain message) into CMS (cipher message) and then publish.  The CMS message contains the information needed (the key id) to convert the cipher message into a plain message.

**Comment by RangerMauve** [comment]
So the goal is to get IPFS to seamlessly integrate with rfc5652 messages for every level of the API?

**Comment by richardschneider** [comment]
@RangerMauve Yes, that is the goal. See the [keystore spec](https://github.com/ipfs/specs/tree/master/keystore#other-interface-changes) for suggested API changes.

**Comment by richardschneider** [comment]
Thanks to a short discussion with @diasdavid, a few things have been clarified

- This a **key chain** 
- It uses a *key store* to save/retrieve an encrypted key

The *key store* is some implementation of [interface-datastore](https://github.com/ipfs/interface-datastore/).

**Note:** 16 minutes of discussion equates to 5 hours of refactoring!

**Comment by RangerMauve** [comment]
@richardschneider Could you maybe link to the discussion if there's a digital version available?

**Comment by richardschneider** [comment]
@RangerMauve The source is now available at https://github.com/libp2p/js-libp2p-keychain
